#!/bin/bash
umask 0002

if [ "x$JAVA_HOME" = "x" ]; then
    JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64"
fi

MAVEN_HOME="/usr/share/maven"
application_dir="/var/app"

cd $application_dir
"${MAVEN_HOME}/bin/mvn" "$@"
