#!/bin/bash

if [ "x$PHP_INI" != "x" ]; then
    echo "$PHP_INI" | grep "^\/" 
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        PHP_INI="/var/app/${PHP_INI}"
    fi

    if [ -e "$PHP_INI" ]; then
        ln -sf "$PHP_INI" /etc/php5/conf.d/99-app.ini
    fi
fi

if [ "x$XDEBUG_REMOTE_PORT" != "x" ]; then
    sed -i "s/^ *\\(xdebug\\.remote_port\\) *= *.*/\\1=${XDEBUG_REMOTE_PORT}/" /etc/php5/conf.d/90-app.ini
fi

source /etc/apache2/envvars && exec /usr/sbin/apache2 -D FOREGROUND
