#!/bin/bash

script_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

application_dir="/var/app"

if [ "x$APACHE_RUN_USER" = "x" ]; then
    echo "ERROR: The environment variable \"APACHE_RUN_USER\" does not exist."

    exit 1
fi

if [ ! -d "$application_dir" ]; then
    echo "ERROR: \"$application_dir\" does not exist. Mount your PHP project root as \"$application_dir\" on the host."

    exit 1
fi

cd "$application_dir"
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

find "${application_dir}" ! -group $APACHE_RUN_GROUP -exec chgrp $APACHE_RUN_GROUP '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

find "${application_dir}" -type d ! -perm 2775 -exec chmod 2775 '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

find "${application_dir}" -type f ! -perm -g+rw -exec chmod g+rw '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

if [ ! -e "${application_dir}/composer.phar" ]; then
    sudo -u $APACHE_RUN_USER php -r "readfile('https://getcomposer.org/installer');" | sudo -u $APACHE_RUN_USER COMPOSER_HOME="${application_dir}/.composer" php
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        exit $RETVAL
    fi
fi

if [ -e "${application_dir}/composer.phar" ]; then
    sudo -u $APACHE_RUN_USER COMPOSER_HOME="${application_dir}/.composer" php composer.phar self-update
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        exit $RETVAL
    fi

    if [ "x$APP_CREATE_PROJECT" = "x" ]; then
        sudo -u $APACHE_RUN_USER COMPOSER_HOME="${application_dir}/.composer" php composer.phar install --no-interaction
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            exit $RETVAL
        fi
    else
        if [ "x$APP_CREATE_PROJECT_VERSION" = "x" ]; then
            sudo -u $APACHE_RUN_USER COMPOSER_HOME="${application_dir}/.composer" php -d memory_limit=-1 composer.phar create-project --no-interaction "$APP_CREATE_PROJECT" /tmp/app
        else
            sudo -u $APACHE_RUN_USER COMPOSER_HOME="${application_dir}/.composer" php -d memory_limit=-1 composer.phar create-project --no-interaction "$APP_CREATE_PROJECT" /tmp/app "$APP_CREATE_PROJECT_VERSION"
        fi
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            exit $RETVAL
        fi

        $( shopt -s dotglob nullglob && mv /tmp/app/* "${application_dir}" )
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            exit $RETVAL
        fi

        rm -rf /tmp/app
    fi
fi

find "${application_dir}" ! -group $APACHE_RUN_GROUP -exec chgrp $APACHE_RUN_GROUP '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

find "${application_dir}" -type d ! -perm 2775 -exec chmod 2775 '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

find "${application_dir}" -type f ! -perm -g+rw -exec chmod g+rw '{}' \;
RETVAL=$?
if [ $RETVAL -ne 0 ]; then
    exit $RETVAL
fi

if [ "x$APP_INIT_SCRIPT" != "x" ]; then
    echo "$APP_INIT_SCRIPT" | grep "^\/"
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        APP_INIT_SCRIPT="${application_dir}/${APP_INIT_SCRIPT}"
    fi

    if [ -x "$APP_INIT_SCRIPT" ]; then
        "$APP_INIT_SCRIPT"
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            exit $RETVAL
        fi
    fi
fi
