#!/bin/bash

. /usr/local/sbin/system-locale.sh
. /usr/local/sbin/system-timezone.sh

if [ "x$LANG" != "x" ]; then
    _system_locale_configure "$LANG"
fi

if [ "x$TZ" != "x" ]; then
    _system_timezone_configure "$TZ"
fi

/usr/local/sbin/mysql-init
